// Generated by CoffeeScript 1.6.3
(function() {
  var _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.HandView = (function(_super) {
    __extends(HandView, _super);

    function HandView() {
      _ref = HandView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    HandView.prototype.className = 'hand';

    HandView.prototype.template = function(obj) {
      var temp;
      temp = $('#hand').html();
      return Mustache.render(temp, obj);
    };

    HandView.prototype.initialize = function() {
      var _this = this;
      this.collection.on('add remove change reset', function() {
        return _this.render();
      });
      return this.render();
    };

    HandView.prototype.render = function() {
      var obj, str;
      this.$el.children().detach();
      obj = {
        isDealer: this.collection.isDealer,
        scores: this.collection.scores().join(", ")
      };
      str = this.template(obj);
      this.$el.html(str);
      return this.$el.append(this.collection.map(function(card) {
        return new CardView({
          model: card
        }).$el;
      }));
    };

    return HandView;

  })(Backbone.View);

}).call(this);

/*
//@ sourceMappingURL=HandView.map
*/
