// Generated by CoffeeScript 1.6.3
(function() {
  var _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.Hand = (function(_super) {
    __extends(Hand, _super);

    function Hand() {
      _ref = Hand.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Hand.prototype.model = Card;

    Hand.prototype.initialize = function(array, deck, isDealer) {
      this.deck = deck;
      this.isDealer = isDealer;
      return this.canHit = true;
    };

    Hand.prototype.hit = function() {
      if (this.canHit) {
        this.add(this.deck.pop()).last();
        if (this.scores().length === 1 && this.scores()[0] > 21) {
          this.canHit = false;
          this.trigger("bust");
        }
        if (this.scores().length === 1 && this.scores()[0] === 21) {
          return this.stand();
        }
      }
    };

    Hand.prototype.stand = function() {
      if (this.canHit) {
        this.canHit = false;
        return this.trigger("finished");
      }
    };

    Hand.prototype.scores = function() {
      var hasAce, score;
      hasAce = this.reduce(function(memo, card) {
        return memo + (card.get('value') === 1 ? 1 : 0);
      }, 0);
      score = this.reduce(function(score, card) {
        return score + (card.get('revealed') ? card.get('value') : 0);
      }, 0);
      if (hasAce && (score + 10 <= 21)) {
        return [score, score + 10];
      } else {
        return [score];
      }
    };

    Hand.prototype.play = function() {
      this.first().set('revealed', true);
      while (this.scores()[this.scores().length - 1] < 17) {
        this.hit();
      }
      return this.trigger("finished");
    };

    return Hand;

  })(Backbone.Collection);

}).call(this);

/*
//@ sourceMappingURL=Hand.map
*/
