// Generated by CoffeeScript 1.6.3
(function() {
  $(document).ready(function() {
    window.app = new App();
    return new AppView({
      model: app
    }).$el.appendTo('body');
  });

}).call(this);

/*
//@ sourceMappingURL=main.map
*/
